### ISSUE TITLE
[client]: windows 8 build failed!

### ISSUE THREAD

**Issue by chan18** [scanf/pastedrop#13]
i was setting up this project in my local environment windows, initially i started with [ doc ](https://microsoft.github.io/reactxp/docs/getting-started.html), cloned this [repo](https://microsoft.github.io/reactxp/docs/getting-started.html) as mentioned in the doc then successfully installed helloworld reactxp app build was successful. I am not sure what causing the issue though in my windows environment? is this build working for other windows environment? or is it me? this is my error log.

>npm run start:web

`npm run start:web

> pastedrop@0.0.1 start:web C:\Users\Naga Sai\Documents\opensource\pastedrop\pastedrop
> cross-env platform=web webpack-dev-server --config=web/webpack/dev.js --progress --colors --mode=development

 10% building modules 1/1 modules 0 activeevents.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:9999
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at doListening (net.js:1397:7)
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\node.exe" "C:\\node_modules\\npm\\bin\\npm-cli.js" "run" "start:web"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! pastedrop@0.0.1 start:web: `cross-env platform=web webpack-dev-server --config=web/webpack/dev.js --progress --colors --mode=development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pastedrop@0.0.1 start:web script 'cross-env platform=web webpack-dev-server --config=web/webpack/dev.js --progress --colors --mode=development'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pastedrop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env platform=web webpack-dev-server --config=web/webpack/dev.js --progress --colors --mode=development
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pastedrop
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pastedrop
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Naga Sai\Documents\opensource\pastedrop\pastedrop\npm-debug.log`

> npm-debug.log

`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\node.exe',
1 verbose cli   'C:\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start:web' ]
2 info using npm@4.0.5
3 info using node@v7.4.0
4 verbose run-script [ 'prestart:web', 'start:web', 'poststart:web' ]
5 info lifecycle pastedrop@0.0.1~prestart:web: pastedrop@0.0.1
6 silly lifecycle pastedrop@0.0.1~prestart:web: no script for prestart:web, continuing
7 info lifecycle pastedrop@0.0.1~start:web: pastedrop@0.0.1
8 verbose lifecycle pastedrop@0.0.1~start:web: unsafe-perm in lifecycle true
9 verbose lifecycle pastedrop@0.0.1~start:web: PATH: C:\node_modules\npm\bin\node-gyp-bin;C:\Users\Naga Sai\Documents\opensource\pastedrop\pastedrop\node_modules\.bin;C:\Users\Naga Sai\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\usr\bin;C:\Program Files\ConEmu\ConEmu\Scripts;C:\Program Files\ConEmu;C:\Program Files\ConEmu\ConEmu;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\TortoiseSVN\bin;C:\ProgramData\ComposerSetup\bin;C:\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit;C:\Program Files\Git\cmd;C:\Users\Naga Sai\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle pastedrop@0.0.1~start:web: CWD: C:\Users\Naga Sai\Documents\opensource\pastedrop\pastedrop
11 silly lifecycle pastedrop@0.0.1~start:web: Args: [ '/d /s /c',
11 silly lifecycle   'cross-env platform=web webpack-dev-server --config=web/webpack/dev.js --progress --colors --mode=development' ]
12 silly lifecycle pastedrop@0.0.1~start:web: Returned: code: 1  signal: null
13 info lifecycle pastedrop@0.0.1~start:web: Failed to exec start:web script
14 verbose stack Error: pastedrop@0.0.1 start:web: `cross-env platform=web webpack-dev-server --config=web/webpack/dev.js --progress --colors --mode=development`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid pastedrop@0.0.1
16 verbose cwd C:\Users\Naga Sai\Documents\opensource\pastedrop\pastedrop
17 error Windows_NT 6.3.9600
18 error argv "C:\\node.exe" "C:\\node_modules\\npm\\bin\\npm-cli.js" "run" "start:web"
19 error node v7.4.0
20 error npm  v4.0.5
21 error code ELIFECYCLE
22 error pastedrop@0.0.1 start:web: `cross-env platform=web webpack-dev-server --config=web/webpack/dev.js --progress --colors --mode=development`
22 error Exit status 1
23 error Failed at the pastedrop@0.0.1 start:web script 'cross-env platform=web webpack-dev-server --config=web/webpack/dev.js --progress --colors --mode=development'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the pastedrop package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     cross-env platform=web webpack-dev-server --config=web/webpack/dev.js --progress --colors --mode=development
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs pastedrop
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls pastedrop
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by aalemayhu** [comment]
Make sure nothing else is using the port (`9999`). Also make sure all dependencies are installer (`npm install`). We can look at this together during stream, if not resolved by then.
